### ISSUE TITLE
I don't find the Integration in my HA

### ISSUE THREAD

**Issue by silversmarty** [hacf-fr/hass-ecoledirecte#1]
Hello,
as i'm trying to install this integration to test it, I can't find it in the Integration list.
Is there any additional filter to make this integration appear in my list?

![image](https://github.com/hacf-fr/hass-ecoledirecte/assets/17980711/6966956a-d200-4063-ad32-f915b9f0e8f4)

Thanks

**Comment by Giga77** [comment]
Hi
First you need to copy the folder "Ecole directe" to the folder custom_compents. Then restart HA.
And after it should appear.

**Comment by silversmarty** [comment]
Thanks a lot, it works !
