### ISSUE TITLE
Contenu du Homework incomplet

### ISSUE THREAD

**Issue by silversmarty** [hacf-fr/hass-ecoledirecte#18]
Bonjour,
sur certains éléments de homework, le contenu est tronqué :

- Sur Ecole Directe :
![Capture d'écran 2024-05-29 121927](https://github.com/hacf-fr/hass-ecoledirecte/assets/17980711/25f88349-0ee1-45e8-b2b5-cd996fbec701)
 
- Sur Home Assistant : 
![Capture d'écran 2024-05-29 121817](https://github.com/hacf-fr/hass-ecoledirecte/assets/17980711/36b1f1c6-2202-44c5-94bf-40f6dfe341c2)

Est-ce que d'autres ont ce problème ? Je ne vois pas trop ce qi peut coincer, pas de coupure sur un caractère spécial ou autre ...

Merci !
Paul

**Comment by Giga77** [comment]
Hello

C'est normal tu regardes le champ "short_description"
Dans le champs "description", il y a tout le contenu.

**Comment by silversmarty** [comment]
Quel idiot ! Désolé de t'avoir dérangé pour un truc aussi trivial !
Merci !
