### ISSUE TITLE
Le flux de configuration n'a pas pu être chargé

### ISSUE THREAD

**Issue by julienvedebe** [hacf-fr/hass-ecoledirecte#2]
Bonjour,

J'ai copié le dossier ecole_directe dans mon répertoire customer_components.

Après restart je vois bien l'intégration en cherchant "école" mais quand je clique dessus j'ai le message d'erreur suivant (CF capture d'écran).

![image](https://github.com/hacf-fr/hass-ecoledirecte/assets/12135264/c5f38258-ba53-420e-a23f-a2d66e732ade)

**Comment by Giga77** [comment]
Salut

Il faut copier le dossier "ecole_directe" dans le répertoire **custom_components** (et non customer_components).
Il ne faut pas renommer les répertoire.

**Comment by julienvedebe** [comment]
C'est une erreur de frappe de ma part mais mon dossier est bien custom_components

**Comment by Giga77** [comment]
Quelle est la version de HA utilisée ?

Essaie de supprimer le répertoire "ecole_directe", redémarre HA, copie le répertoire "ecole_directe" et redémarre HA.

**Comment by julienvedebe** [comment]
Home Assistant 2023.7.3
Interface utilisateur : 20230705.1 - latest

Je vais tenter en supprimant ce soir merci encore

**Comment by julienvedebe** [comment]
Celà venait de ma version de HA j'ai réinstallé HASSIO sur un autre ordi et là çà fonctionne merci encore
