### ISSUE TITLE
Double compte

### ISSUE THREAD

**Issue by silversmarty** [hacf-fr/hass-ecoledirecte#23]
Bonjour,
j'ai deux enfants, chacun dans une école différente : les informaticiens de chaque école m'ont donc chacun créé un compte (!), sur lequel j'ai un enfant.

Ecole directe gère le lien entre deux comptes (en spécifiant dans le compte n°1 le login et mdp du compte n°2), mais j'ignore comment cette extension gère cela. Et je ne vois pas où/comment mettre deux comptes dans les paramètres de l'extension.
![image](https://github.com/user-attachments/assets/0cce2dbf-5635-4e0f-87c9-bfaa339cc401)

Ma questions est la suivante : comment gérer deux comptes différents dans l'extension ? J'ai l'impression que le lien entre les comptes n'est pas géré par l'extension (mon compte n°2 n'apparait pas dans HA)

Merci

**Comment by Giga77** [comment]
Bonjour,

ç'est un cas particulier...
Je vais rajouter la possiblité de rajouter plusieurs comptes.
On verra si les données apparaissent.

**Comment by flofly13008** [comment]
Salut, bravo pour le développement fastidieux, car j'ai lu l'ensemble des fichiers et vraiment chapeau. Je suis dans le même cas, double compte, deux login et deux MdP. Merci bien pour ton aide.

**Comment by Giga77** [comment]
Dans la version 0.3.9, vous pouvez définir plusieurs comptes.
https://github.com/hacf-fr/hass-ecoledirecte/releases/tag/v0.3.9

Dites moi si ça voous convient.

**Comment by flofly13008** [comment]
Salut GiGa. Comment télécharger la pre-release ?

**Comment by Giga77** [comment]
Regarde ici : https://www.hacf.fr/ecole-directe/#version-pre-relase

**Comment by flofly13008** [comment]
salut Giga77, après avoir testé ton code, je n'arrive pas à déclarer mes sensors peux tu me dire si je me trompe ? : 

- platform: event
  student: Manon Barone
  entity_id: sensor.ecole_directe_manon_xxx_
  sensors:
    - grades
    - homework
    - evaluations
    - timetable_today
    - timetable_tomorrow
    - timetable_next_day
    - timetable_period
    - timetable_period_1
    - timetable_period_2
    - absences
    - retards
    - sanctions
    - encouragements

- platform: event
  student: Louis Barone
  entity_id: sensor.ecole_directe_louis_xxx_
  sensors:
    - grades
    - homework
    - evaluations
    - timetable_today
    - timetable_tomorrow
    - timetable_next_day
    - timetable_period
    - timetable_period_1
    - timetable_period_2
    - absences
    - retards
    - sanctions
    - encouragements

**Comment by Giga77** [comment]
Tu n'as pas besoin de déclarer de sensors. L'intégration le fait automatiquement.
Poste sur le forum de HACF : https://forum.hacf.fr/t/article-integration-ecole-directe/47645
ç'est plus facile pour échanger.

**Comment by flofly13008** [comment]
Fait merci, j'attends tes réponses si dispo.

**Comment by silversmarty** [comment]
Je viens de l'installer avec succès, merci @Giga77 pour ta réactivité !!
