### ISSUE TITLE
attributes are too big!

### ISSUE THREAD

**Issue by Dites33** [hacf-fr/hass-ecoledirecte#24]
Bonjour

Core : 2024.8.2
Supervisor : 2024.08.0
Operating System : 13.0
Interface utilisateur : 20240809.0

**Depuis avant hier je n'ai plus les devoirs de mon fils. 
La carte pronote (que j'utilise avec ecoledirecte) indique PAS DE DEVOIRS**

Quand je vais dans les outils de dev, sur le sensor homework je vois ceci

updated_at: 2024-09-11T17:45:48.208064+00:00
homework:  
todo_counter: 13
friendly_name: ecole_directe_xxxxxx_homework

Dans les logs je vois 3 erreurs de type avertissement.

Cette erreur provient d'une intégration personnalisée

_Enregistreur: custom_components.ecole_directe.coordinator
Source: custom_components/ecole_directe/coordinator.py:180
intégration: Ecole Directe (documentation, problèmes)
S'est produit pour la première fois: 6 septembre 2024 à 10:52:55 (249 occurrences)
Dernier enregistrement: 19:45:46
Error getting grades from ecole directe: 'NoneType' object has no attribute 'replace'_

_Enregistreur: custom_components.ecole_directe.coordinator
Source: custom_components/ecole_directe/coordinator.py:312
intégration: Ecole Directe (documentation, problèmes)
S'est produit pour la première fois: 6 septembre 2024 à 10:52:56 (249 occurrences)
Dernier enregistrement: 19:45:48
Error getting vie scolaire from ecole directe: Error with URL:[https://api.ecoledirecte.com/v3/eleves/8129/viescolaire.awp?verbe=get&v=4.57.1] - Code 210: Aucune donnée à afficher !_

**Enregistreur: custom_components.ecole_directe.sensor
Source: custom_components/ecole_directe/sensor.py:215
intégration: Ecole Directe (documentation, problèmes)
S'est produit pour la première fois: 9 septembre 2024 à 15:22:19 (103 occurrences)
Dernier enregistrement: 19:45:48
[xxxxxx_homework] attributes are too big! []**

Je comprends donc qu'il a trop de devoirs (ou des profs trop prolixes :)), comment pouvons nous corriger cela ?

MERCI :)

**Comment by Giga77** [comment]
Bonjour

La solution la plus simple : Il faut dire aux profs de donner moins de devoirs 😆 

Plus sérieusement, je pense qu'il faut diviser les devoirs en plusieurs sensors, ou sinon réduire les informations retenues.

**Comment by myfp31** [comment]
Bonjour,

J'ai exactement le même problème et dans mon cas, je suppose que le problème provient des devoirs qui contiennent des images (couverture des livres à acheter, photo des écouteurs filaires pour l'évaluation nationale....).

Pour confirmer cela, j'ai doublé la valeur de MAX_STATE_ATTRS_BYTES dans const.py. Ce qui est certainement une très mauvaise idée mais temporairement, cela a permis de débloquer la situation mais j'ai un nouveau message de warning plus général 👎 :

> State attributes for sensor.ecole_directe_xxxxxx_homework exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

J'ai ensuite cherché la taille de chacune des descriptions des devoirs et l'une d'elle fait 22175.... ce qui pourrait être un devoir d'une petite trentaine de pages....
est-ce que cela vous parait cohérent?
je pensais utiliser PIL pour retirer l'image de la chaine de caractère. est-ce que cela pourrait être une solution ?

Merci 

PS : merci pour l'intégration qui marche super bien.

**Comment by myfp31** [comment]
Bonjour,

Je confirme que dans mon cas, c'est bien les images embarquées qui ont provoqué l'erreur.....

pour contourner temporairement le problème, je suis revenu à la valeur MAX_STATE_ATTRS_BYTES  par défaut, j'ai importé la librairie re dans sensor.py  et j'ai ajouté ces lignes entre `todo_counter += 1` et `attributes.append(homework)` dans la boucle
`if not homework["done"]`

```
pattern = r"<img.*?src=[\"|\']data:(.*?)[\"|\'].*?>"  # match img with source data
repl = '<strong style="color: #FF0000">[Image non importee]</strong>'  # replace with default message
homework['description'] = re.sub(pattern, repl, homework['description'])
```
Le but est de remplacer les images embarquée (scr="data....) par un texte court

Après redémarrage, les devoirs apparaissent et à la place des images, j'ai bien image non importée
![image](https://github.com/user-attachments/assets/19cedf6c-266a-4579-b2b9-16e6e2b74e1c)

ce n'est pas formidable mais je ne sais pas vraiment comment faire mieux. 
Il est peut-être possible d'exporter les images dans un fichier et des les afficher mais c'est bien au delà de mes compétences actuelles.

En espérant que cela puisse aider

**Comment by ctournayre** [comment]
Bonjour,
ce que je ne comprend pas c'est pourquoi je n'ai pas tous les fichiers get_homeworks_by_date_x.json (seulement le 1er sur 7 attendus). Dans le code de get_homeworks(...) je pensais que tous les .json étaient récupérés et la variable contenant tout retournée à la fin. Comment se fait-il que ca plante "au milieu" sans que tous les json ne soient récupérés. Alors que l'erreur est dans EDHomeworksSensor() ?

**Comment by Giga77** [comment]
> Bonjour,
> 
> Je confirme que dans mon cas, c'est bien les images embarquées qui ont provoqué l'erreur.....
> 
> pour contourner temporairement le problème, je suis revenu à la valeur MAX_STATE_ATTRS_BYTES par défaut, j'ai importé la librairie re dans sensor.py et j'ai ajouté ces lignes entre `todo_counter += 1` et `attributes.append(homework)` dans la boucle `if not homework["done"]`
> 
> ```
> pattern = r"<img.*?src=[\"|\']data:(.*?)[\"|\'].*?>"  # match img with source data
> repl = '<strong style="color: #FF0000">[Image non importee]</strong>'  # replace with default message
> homework['description'] = re.sub(pattern, repl, homework['description'])
> ```
> 
> Le but est de remplacer les images embarquée (scr="data....) par un texte court
> 
> Après redémarrage, les devoirs apparaissent et à la place des images, j'ai bien image non importée ![image](https://private-user-images.githubusercontent.com/9633358/366661463-19cedf6c-266a-4579-b2b9-16e6e2b74e1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTQ4OTQsIm5iZiI6MTcyNzQ1NDU5NCwicGF0aCI6Ii85NjMzMzU4LzM2NjY2MTQ2My0xOWNlZGY2Yy0yNjZhLTQ1NzktYjJiOS0xNmU2ZTJiNzRlMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTYyOTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI0ODNhOGJmMmYzOWNlZTVmMTdjYTBkNGU3ODkyNzA3ZGU3ZGI0Y2EwMzBjMWY0NjU4MDJkZjE2NTEwODRmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._mhf9kmTYNcoxoQ8cPhG0Pczmh9jgdZ5_5BpJtGnjbU)
> 
> ce n'est pas formidable mais je ne sais pas vraiment comment faire mieux. Il est peut-être possible d'exporter les images dans un fichier et des les afficher mais c'est bien au delà de mes compétences actuelles.
> 
> En espérant que cela puisse aider

As-tu essayer de retirer les tags HTML : https://www.hacf.fr/ecole-directe/#retrait-des-tags-htm ?

**Comment by myfp31** [comment]
> > Bonjour,
> > Je confirme que dans mon cas, c'est bien les images embarquées qui ont provoqué l'erreur.....
> > pour contourner temporairement le problème, je suis revenu à la valeur MAX_STATE_ATTRS_BYTES par défaut, j'ai importé la librairie re dans sensor.py et j'ai ajouté ces lignes entre `todo_counter += 1` et `attributes.append(homework)` dans la boucle `if not homework["done"]`
> > ```
> > pattern = r"<img.*?src=[\"|\']data:(.*?)[\"|\'].*?>"  # match img with source data
> > repl = '<strong style="color: #FF0000">[Image non importee]</strong>'  # replace with default message
> > homework['description'] = re.sub(pattern, repl, homework['description'])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Le but est de remplacer les images embarquée (scr="data....) par un texte court
> > Après redémarrage, les devoirs apparaissent et à la place des images, j'ai bien image non importée ![image](https://private-user-images.githubusercontent.com/9633358/366661463-19cedf6c-266a-4579-b2b9-16e6e2b74e1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTQ4OTQsIm5iZiI6MTcyNzQ1NDU5NCwicGF0aCI6Ii85NjMzMzU4LzM2NjY2MTQ2My0xOWNlZGY2Yy0yNjZhLTQ1NzktYjJiOS0xNmU2ZTJiNzRlMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTYyOTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI0ODNhOGJmMmYzOWNlZTVmMTdjYTBkNGU3ODkyNzA3ZGU3ZGI0Y2EwMzBjMWY0NjU4MDJkZjE2NTEwODRmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._mhf9kmTYNcoxoQ8cPhG0Pczmh9jgdZ5_5BpJtGnjbU)
> > ce n'est pas formidable mais je ne sais pas vraiment comment faire mieux. Il est peut-être possible d'exporter les images dans un fichier et des les afficher mais c'est bien au delà de mes compétences actuelles.
> > En espérant que cela puisse aider
> 
> As-tu essayer de retirer les tags HTML : https://www.hacf.fr/ecole-directe/#retrait-des-tags-htm ?

Bonjour,

Non, et malheureusement, je n'ai plus d'image dans les devoirs actuels.
Je ne vois pas comment retrouver le même cas, à part attendre.
Si tu as une idée, je suis prêt à le tenter.

**Comment by ctournayre** [comment]
En fait pour ce problème je propose 2 solutions relativement simple à mettre en place :


- Tout simplement supprimer la verification de la taille des attributs (supprimer le lignes 213 à 215 de sensor.py) 
  - avantage : ça fonctionne très bien et c'est safe, juste que ca ne sera pas sauvé dans le recorder
  - inconvenient : affiche un warning dans les logs  `WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.ecole_directe_xxx_yyy_homework exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored`
  - solution : supprimer ce sensor du recorder
 ```
  recorder:
   exclude:
     entity_globs:
       - sensor.ecole_directe_*_homework
 ```
- Sinon ajouter les devoirs et s’arrêter juste avant celui faisant overflow les attributes, à chaque appel a `attributes.append(homework)` (ligne 203 de sensor.py) verifier que != de `is_too_big(attributes)` dans ce cas on depile le dernier element et il ne manquera que quelques devoirs.
  - avantage: rien à faire coté user
  - inconvenient : il manque des devoirs et pas forcément les plus loin dans le temps.
 
 
 Personnellement la solution un me plait le plus et est très facile à mettre en place coté dev

**Comment by Giga77** [comment]
@ctournayre 
Ton analyse n'est pas correcte. Même si on enlève la verification de la taille des attributs, HA va la faire et il n'y aura pas d'attributs de toute façon.
Pour le recorder, je suis d'accord, il ne faudrait pas que ça reste dans le recorder. Mais je ne veux pas y toucher, car ç'est à chacun de le gérer comme il le souhaite.
Pour moi, la solution 1 ne fonctionne pas.

Les devoirs sont triés par date lors de la récupération des données (ligne 445 du fichier ecole_directe_helper.py).
Ma solution : garder le sensor Homework, et créer 3 sensors pour les 3 prochaines semaines.

**Comment by ctournayre** [comment]
Pour l'avoir testé, je te garanti que ça résolvais le problème. Après pas de soucis, j'aime bien ta solution avec 3 homework différents.

**Comment by myfp31** [comment]
> > > Bonjour,
> > > Je confirme que dans mon cas, c'est bien les images embarquées qui ont provoqué l'erreur.....
> > > pour contourner temporairement le problème, je suis revenu à la valeur MAX_STATE_ATTRS_BYTES par défaut, j'ai importé la librairie re dans sensor.py et j'ai ajouté ces lignes entre `todo_counter += 1` et `attributes.append(homework)` dans la boucle `if not homework["done"]`
> > > ```
> > > pattern = r"<img.*?src=[\"|\']data:(.*?)[\"|\'].*?>"  # match img with source data
> > > repl = '<strong style="color: #FF0000">[Image non importee]</strong>'  # replace with default message
> > > homework['description'] = re.sub(pattern, repl, homework['description'])
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Le but est de remplacer les images embarquée (scr="data....) par un texte court
> > > Après redémarrage, les devoirs apparaissent et à la place des images, j'ai bien image non importée ![image](https://private-user-images.githubusercontent.com/9633358/366661463-19cedf6c-266a-4579-b2b9-16e6e2b74e1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTQ4OTQsIm5iZiI6MTcyNzQ1NDU5NCwicGF0aCI6Ii85NjMzMzU4LzM2NjY2MTQ2My0xOWNlZGY2Yy0yNjZhLTQ1NzktYjJiOS0xNmU2ZTJiNzRlMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTYyOTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI0ODNhOGJmMmYzOWNlZTVmMTdjYTBkNGU3ODkyNzA3ZGU3ZGI0Y2EwMzBjMWY0NjU4MDJkZjE2NTEwODRmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._mhf9kmTYNcoxoQ8cPhG0Pczmh9jgdZ5_5BpJtGnjbU)
> > > ce n'est pas formidable mais je ne sais pas vraiment comment faire mieux. Il est peut-être possible d'exporter les images dans un fichier et des les afficher mais c'est bien au delà de mes compétences actuelles.
> > > En espérant que cela puisse aider
> > 
> > 
> > As-tu essayer de retirer les tags HTML : https://www.hacf.fr/ecole-directe/#retrait-des-tags-htm ?
> 
> Bonjour,
> 
> Non, et malheureusement, je n'ai plus d'image dans les devoirs actuels. Je ne vois pas comment retrouver le même cas, à part attendre. Si tu as une idée, je suis prêt à le tenter.

Bonjour @Giga77 

Je me permets de répondre même si le cas a été clôturé.
En retirant les tags HTML, cela fonctionne pour les images "importées" dans mon cas.

Merci, cordialement,
