### ISSUE TITLE
heure de debut et fin fausse sur l'agande des enfants

### ISSUE THREAD

**Issue by roumano** [hacf-fr/hass-ecoledirecte#25]
Sur l'agande afficher via `custom:pronote-timetable-card`, l'heure de debut et fin est fausse, c'est 2h du matin pour les deux

![bug_ecole_direct-aganda](https://github.com/user-attachments/assets/b08bfdc6-bfa6-443d-977d-fa50d5833ebf)

Meme sur les screenshot de l'article ( https://hacf.fr/ecole-directe/ ) c'est le meme souci , ...

Pourtant le sensor a l'information :  
```
sensor.ecole_directe_xxx_yyy_timetable_next_day

day_start_at: "2024-09-19T08:20:00"
day_end_at: "2024-09-19T16:30:00"
lunch_break_start_at: "2024-09-19T12:15:00"
lunch_break_end_at: "2024-09-19T13:35:00"
```

**Comment by Giga77** [comment]
Il y a eu une modification dans la carte de Pronote : https://github.com/delphiki/lovelace-pronote/commit/99e9a283639fa3edec27eb3f6c67c19a94f9883f

Il faut que je fasse des ajustements.

**Comment by Giga77** [comment]
C'est corrigé dans la version 0.3.10 :
https://github.com/hacf-fr/hass-ecoledirecte/releases/tag/v0.3.10
