### ISSUE TITLE
Problème d'attributs dans les timetable

### ISSUE THREAD

**Issue by ptitcicis** [hacf-fr/hass-ecoledirecte#26]
Bonjour,
Merci pour cette super intégration, vraiment pratique pour les parents !

Je rencontre des difficultés dans les attributs pour chaque timetable, au niveau des pauses déjeuner.

Par exemple un de mes fils à cours demain à 12h50 :
- start: '2024-09-19T12:50:00'
end: '2024-09-19T13:45:00'
start_at: '2024-09-19'
end_at: '2024-09-19'
start_time: '12:50'
end_time: '13:45'
lesson: ANGLAIS

Par contre l'attribut de "lunch break" prévoit une fin de pause déjeuner à 13:45 au lien de 12:50 :
Day start at
19 septembre 2024 à 08:00:00
Day end at
19 septembre 2024 à 17:40:00
Lunch break start at
19 septembre 2024 à 11:55:00
Lunch break end at
19 septembre 2024 à 13:45:00

J'ai ce problème aussi bien dans la timetable today que tomorrow.

Est-ce au niveau de l'API que les données sont fausses ?
Quand la pause va plus loin que 14h cela semble juste, par contre quand un cours a lieu entre midi et 14h il semblerait qu'il ne soit pas pris en compte.
J'ai regardé dans l'appli EcoleDirecte, l'emploi du temps est correct.

Merci d'avance pour votre aide !

**Comment by ptitcicis** [comment]
Re,

Je rajoute une capture d'écran de la carte 
![Capture d’écran 2024-09-18 132538](https://github.com/user-attachments/assets/fe403ebe-7b30-4198-bba7-bfa0a0b29147)
La pause déjeuner se promène ailleurs !

Bonne journée

**Comment by Giga77** [comment]
Dans le code, je considère que tous les cours qui commencent avant 13H sont avant le repas.
Je vais essayer d'avoir une configuration pour modifier cette valeur.

**Comment by ptitcicis** [comment]
Super, merci !

**Comment by Giga77** [comment]
L'option est configurable dans cette version :
https://github.com/hacf-fr/hass-ecoledirecte/releases/tag/v0.3.10

**Comment by Giga77** [comment]
corrigé
