### ISSUE TITLE
Affichage des absences

### ISSUE THREAD

**Issue by Dites33** [hacf-fr/hass-ecoledirecte#30]
Je me doute que le probleme vient du côté PRONOTE (en tout cas des cartes pronote que tu recommandes pour l'instant) 

Mon enfant est malade ce jour
L'entité a été mise à jour 

updated_at: 2024-09-24T10:24:15.483441+00:00
absences: 
- date: '2024-09-24'
  type_element: Absence
  display_date: le mardi 24 septembre 2024 de 08:00 à 16:30
  justified: true
  motif: Malade
  commentaire: ''
friendly_name: ecole_directe_xxxxxxxxxxx_absences

La carte PRONOTE affiche cependant : 

![image](https://github.com/user-attachments/assets/2b409ea2-06a2-4e6e-93cb-368a2009f87b)

Comment puis je afficher les informations sans passer par le tag de la carte pronote

type: custom:pronote-absences-card
entity: sensor.ecole_directe_xxxxxxxxx_absences
display_header: true
max_absences: null
child_name: null
title: absences

**Comment by lawlawrent** [comment]
J'ai effectivement le meme soucis.

**Comment by astrayel** [comment]
C'est parce qu'il n'y a plus que l'heure dans start_date et end_date et plus la date en plus.

**Comment by Giga77** [comment]
Les cartes Pronotes ne sont pas adaptées pour ces sensors :

- Absences
- Retards
- Sanctions
- Encouragements

Regardez ici un exemple pour les absences : https://forum.hacf.fr/t/article-integration-ecole-directe/47645/25
