### ISSUE TITLE
attribut start_at dans timetable n'a plus que l'heure

### ISSUE THREAD

**Issue by astrayel** [hacf-fr/hass-ecoledirecte#33]
Bonjour, 
Tout d'abord, merci beaucoup pour ce développement très utile.
Avant la mise à jour précédente, j'avais dans start_date et end_date des timetable le format "2024-09-26T15:55:00". Maintenant, je n'ai plus que l'heure. Ce qui ne me paraît pas très illogique. Néanmoins, maintenant, en particulier pour next_day, il faut aller dans les leçons pour avoir la date de la timetable, ce qui, à contrario, me paraît moins logique.
Je crois que cette mise à jour vient d'un problème avec lunch_break mais est-ce le comportement attendu ou pas. Si oui, y a-t-il moyen de rajouter la date complète dans son propre attribut ou quelque chose comme ça ?

Merci.

**Comment by Giga77** [comment]
Bonjour
Effectivement, j'ai changé ces attributs à cause des cartes Pronote.
Tu peux utiliser les attributs "start" et "end" qui ne sont pas nécessaire à Pronote.
