### ISSUE TITLE
Data dans json mais pas dans attributs (grades)

### ISSUE THREAD

**Issue by Dites33** [hacf-fr/hass-ecoledirecte#40]
Hello @Giga77 

Est il possible de populer car chez moi ils sont dans le json (celui que tu as récupéré) mais pas dans les attributs (ils sont vides)

 class_average: ''
  max: ''
  min: ''

**Comment by Giga77** [comment]
Salut

Dans le fichier que j'ai récupéré, ces informations sont disponibles au niveau de la matière, donc ç'est global.
Mais elles ne sont pas disponibles au niveau de la note individuelle :
![image](https://github.com/user-attachments/assets/8357b472-3cf1-412a-a568-5a9cb43fda88)

**Comment by Dites33** [comment]
Ok vu, pas les yeux en face des trous :D 

possible de faire un sensor avec les infos par matieres ?

**Comment by Giga77** [comment]
Ajout des moyennes par disciplines et de la moyenne générale

Il y a un sensor pour la moyenne générale : sensor.ecole_directe_xxxx_yyyy_moyenne_generale
Et un sensor par discipline : sensor.ecole_directe_xxxx_yyyy_anglais lv1

![image](https://github.com/user-attachments/assets/2c7ba7ed-97f3-4cbe-9598-db189ca1dde0)

![image](https://github.com/user-attachments/assets/5d99a4a3-4f72-474b-a9b1-5aca6f87b547)
