### ISSUE TITLE
Erreur :  attributes are too big

### ISSUE THREAD

**Issue by ChrysMa** [hacf-fr/hass-ecoledirecte#49]
Bonjour
j'ai régulièrement l'erreur suivante reportée.... Qu'en pensez vous ?
Chrys

`Enregistreur: custom_components.ecole_directe.sensor
Source: custom_components/ecole_directe/sensor.py:234
intégration: Ecole Directe ([documentation](https://github.com/hacf-fr/hass-ecoledirecte), [problèmes](https://github.com/hacf-fr/hass-ecoledirecte/issues))
S'est produit pour la première fois: 19 novembre 2024 à 20:33:02 (198 occurrences)
Dernier enregistrement: 21:58:30

    [mxxxx_mxxxx_homework] attributes are too big! []
    [mxxxx_mxxxx__homework_3] attributes are too big! []`

**Comment by Giga77** [comment]
Bonjour

Il y a trop d'informations remonté par Ecole Directe.
Essaie de désactiver les tags HTML : https://www.hacf.fr/ecole-directe/#retrait-des-tags-htm

**Comment by ChrysMa** [comment]
Merci.
J'ai coché... on a voir ce que ça donne.... A suivre
