### ISSUE TITLE
Double Auth

### ISSUE THREAD

**Issue by silversmarty** [hacf-fr/hass-ecoledirecte#5]
Hello,

Je n'arrive pas à me connecter ni à mon compte de parent, ni à mon compte d'élève à cause d'une erreur "double auth" qui apparaît juste après avoir saisis login/mdp.

Est-ce qu'il y a un moyen de passer cette étape ?

![image](https://github.com/hacf-fr/hass-ecoledirecte/assets/17980711/e06d1656-68ee-4205-8778-8faa73ba1615)

Merci

**Comment by Giga77** [comment]
Hello

C'est un problème de cache du navigateur.
Normalement, le message est : "Vérifier le fichier qcm.json."
Il faut aller vérifier les réponses dans le fichier /config/custom_components/ecole_directe/qcm.json
Il y a plus d'informations ici : https://forum.hacf.fr/t/integration-ecole-directe-version-0-2-2/38119/114

**Comment by silversmarty** [comment]
C'est parfait, ça marche ! Merci @Giga77
